export const HotelCardData = {
  title: "Nearby Things To Do",
  filters: true,
  closeCta: "Close",
  modalTitle: "Select a document to view",
  categories: [
    "fitness",
    "golf",
    "area sightseeing",
    "Family & Children’s Activities ",
    "Swimming",
    "spa",
  ],
  cards: [
    {
      category: "fitness",
      cardColorScheme: 1,
      id: "fiteness_nysc",
      title: "New York Sports Club",
      link: false,
      url: "",
      distance: "3.7 Miles",
      description: "",
      files: [
        {
          fileName: "Class Schedule",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "class-schedule",
        },
      ],
    },
    {
      category: "golf",
      cardColorScheme: 1,
      id: "golf_dbgc",
      title: "Dyker Beach Golf Course Brooklyn",
      link: true,
      url: "#",
      distance: "0.2 Miles",
      description:
        "Dyker Beach Golf Course is a beautiful 18-hole championship course located in the heart of Brooklyn, New York, below the shadows of the Verrazano Narrows Bridge. Come experience lush, green fairways and top-notch greens.",
      address: [
        {
          title: "Valley Course",
          text: "18 holes, 6627 yards, Par for course: 72",
        },
        {
          title: "Valley Course",
          text: "18 holes, 6627 yards, Par for course: 72",
        },
      ],
      phone: {
        enabled: true,
        number: "+1 718-836-9722",
        icon: "phone",
      },
      diningFiles: {
        title: "Documents",
        id: "golf_dbgc",
        documents: [
          {
            fileName: "Class Schedule",
            fileUrl: "/resources/files/map.pdf",
          },
        ],
      },
    },
    {
      category: "area sightseeing",
      cardColorScheme: 1,
      id: "area_fnyt",
      title: "Free New York Tours",
      link: true,
      url: "#",
      description: "New York City",
      section: {
        title: "Tour by:",
        text: "Free Tours by Foot",
        isAddress: false,
      },
      phone: {
        enabled: true,
        number: "+1 212-445-7599",
        icon: "phone",
      },
      diningFiles: {
        title: "Documents",
        id: "golf_dbgc",
        documents: [
          {
            fileName: "Class Schedule",
            fileUrl: "/resources/files/map.pdf",
          },
          {
            fileName: "Price List",
            fileUrl: "/resources/files/map.pdf",
          },
          {
            fileName: "Club House Restaurant Menu",
            fileUrl: "/resources/files/map.pdf",
          },
          {
            fileName: "Map",
            fileUrl: "/resources/files/map.pdf",
          },
        ],
      },
    },
    {
      category: "area sightseeing",
      cardColorScheme: 1,
      id: "area_fnyt2",
      title: "Free New York Tours",
      link: true,
      url: "#",
      description: "New York City",
      section: {
        title: "Tour by:",
        text: "Free Tours by Foot",
        isAddress: false,
      },
      phone: {
        enabled: true,
        number: "+1 212-445-7599",
        icon: "phone",
      },
    },
    {
      category: "area sightseeing",
      cardColorScheme: 1,
      id: "area_nyw",
      title: "New York Waterway",
      link: true,
      url: "#",
      description: "New York City",
      section: {
        title: "Tour by:",
        text: "Free Tours by Foot",
        isAddress: false,
      },
      phone: {
        enabled: true,
        number: "+1 212-445-7599",
        icon: "phone",
      },
    },
    {
      category: "area sightseeing",
      cardColorScheme: 1,
      id: "area_nbc",
      title: "NBC Studio Tours",
      link: true,
      url: "#",
      description: "New York City - Multiple Tour Options",
      section: {
        title: "Tour by:",
        text: "City Sights NY Tours",
        isAddress: false,
      },
      phone: {
        enabled: true,
        number: "+1 212-445-7599",
        icon: "phone",
      },
    },
    {
      category: "Family & Children’s Activities ",
      cardColorScheme: 1,
      id: "fca_cpz",
      title: "Central Park Zoo",
      link: false,
      distance: "0.2 Miles",
      description:
        "Set within Central Park, this small zoo features polar bears, sea lions, monkeys & a petting zoo.",
      phone: {
        enabled: true,
        number: "+1-212-704-8834",
        icon: "phone",
      },
    },
    {
      category: "Family & Children’s Activities ",
      cardColorScheme: 1,
      id: "fca_agp",
      title: "American Girl Place",
      link: false,
      distance: "0.2 Miles",
      description:
        "Much more than a store, it's the place where imaginations soar from boutiques to special events.",
      phone: {
        enabled: true,
        number: "+1-212-704-8834",
        icon: "phone",
      },
    },
    {
      category: "golf",
      cardColorScheme: 1,
      id: "golf_gcc",
      title: "The Golf Club at Chelsea Piers",
      link: true,
      url: "#",
      distance: "0.2 Miles",
      description:
        "The Golf Club at Chelsea Piers, Manhattan's only multi-tiered, year-round outdoor driving range, offers the unique opportunity to hit full shots, practice putting and take lessons from top golf professionals.",
      viewDocuments: "View {{count}} Documents",
      documentIcon: "overview",
      phone: {
        enabled: true,
        number: "+960 676 6333",
        icon: "phone",
      },
      files: [
        {
          fileName: "Price List",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "price-list",
        },
        {
          fileName: "Club House Restaurant Menu",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "club-house",
        },
        {
          fileName: "Map",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "map",
        },
      ],
    },
    {
      category: "Swimming",
      cardColorScheme: 1,
      id: "swimming_agp",
      title: "American Girl Place",
      distance: "25 Miles",
    },
    {
      category: "Swimming",
      cardColorScheme: 1,
      id: "swimming_ci",
      title: "Coney Island",
      distance: "20 Miles",
    },
    {
      category: "spa",
      cardColorScheme: 1,
      id: "spa_ssb",
      title: "Salon & Spa Botanica",
      link: false,
      url: "",
      distance: "0.2 Miles",
      description:
        "Whether your needs are relaxation, beautification or therapeutic, we can help. Our team at Salon and Spa Botanica is committed to giving you exceptional customer service and strive to provide you with and unforgettable salon and day spa experience.",
      viewDocuments: "View {{count}} Documents",
      phone: {
        enabled: true,
        number: "+1-212-704-8834",
        icon: "phone",
      },
      links: [
        {
          text: "123 Street Name, City, ST 12345",
          redirectUrl: "#",
          icon: "location",
        },
        {
          text: "Open for Breakfast & Lunch",
          icon: "clock",
        },
      ],
      files: [
        {
          fileName: "Price List",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "price-list",
        },
        {
          fileName: "Cafe Menu",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "cafe-menu",
        },
      ],
      ctaEnabled: true,
      ctaText: "Book Now",
      ctaUrl: "#",
    },
    {
      category: "area sightseeing",
      cardColorScheme: 1,
      id: "area_mce",
      title: "Manhattan Comprehensive Express",
      link: true,
      url: "#",
      description: "New York City - Multiple Tour Options",
      section: {
        title: "Tour by:",
        text: "City Sights NY Tours",
        isAddress: false,
      },
      phone: {
        enabled: true,
        number: "+1 212-445-7599",
        icon: "phone",
      },
      files: [
        {
          fileName: "Price List",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "price-list-1",
        },
        {
          fileName: "Club House Restaurant Menu",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "club-house-1",
        },
        {
          fileName: "Map",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "map-1",
        },
        {
          fileName: "Test",
          redirectUrl: "/resources/files/map.pdf",
          icon: "overview",
          fileId: "test",
        },
      ],
    },
    {
      category: "area sightseeing",
      cardColorScheme: 1,
      id: "area_csb",
      title: "City Sightseeing BusTours",
      link: true,
      url: "#",
      description: "New York City - Multiple Tour Options",
      section: {
        title: "Tour by:",
        text: "City Sights NY Tours",
        isAddress: false,
      },
      phone: {
        enabled: true,
        number: "+1 212-445-7599",
        icon: "phone",
      },
    },
    {
      category: "Family & Children’s Activities ",
      cardColorScheme: 1,
      id: "fca_mtw",
      title: "Madame Tussaud's Wax Museum",
      link: false,
      distance: "0.2 Miles",
      description:
        "More than just a wax museum, the best family attraction in New York.",
      phone: {
        enabled: true,
        number: "+1-212-704-8834",
        icon: "phone",
      },
    },
    {
      category: "Family & Children’s Activities ",
      cardColorScheme: 1,
      id: "fca_dts",
      title: "Disney Times Square Store",
      link: false,
      distance: "0.2 Miles",
      description:
        "Disney retail chain featuring official character toys, clothes, collectibles & more.",
      phone: {
        enabled: true,
        number: "+1-212-704-8834",
        icon: "phone",
      },
    },
  ],
};
